name: Deploy with genezio installed from sources

on:
  workflow_dispatch:
    inputs:
      genezio-branch:
        description: 'The branch to use for genezio'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Fetch genezio from repository
        uses: actions/checkout@v4
        with:
          repository: genez-io/genezio
          ref: ${{ github.event.inputs.genezio-branch }}
          path: genezio

      - name: Build genezio
        working-directory: genezio
        run: |
          npm install
          npm run install-locally

      - name: Login with genezio
        run: genezio login ${{ secrets.GENEZIO_TOKEN }}

      - name: Deploy
        env:
          MY_CUSTOM_SECRET: ${{ secrets.MY_CUSTOM_SECRET }}
        run: MY_SECRET=$MY_CUSTOM_SECRET genezio deploy
