name: Deploy with genezio installed from npmjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Save NODE_VERSION
        run: echo "NODE_VERSION=$(node -v | cut -c 2-)" >> $GITHUB_ENV

      - name: Cache npm binaries to avoid rebuilding genezio
        id: cache-genezio-binary
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/node/${{env.NODE_VERSION}}
          key: ${{ runner.os }}-genezio-binary
          restore-keys: |
            ${{ runner.os }}-${{env.NODE_VERSION}}-genezio-binary


      - uses: Genez-io/genezio-github-action@v2
        if: steps.cache-genezio-binary.outputs.cache-hit != 'true'
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}

      - name: Deploy
        env:
          MY_CUSTOM_SECRET: ${{ secrets.MY_CUSTOM_SECRET }}
        run: MY_SECRET=$MY_CUSTOM_SECRET genezio deploy
