name: Deploy with genezio installed from npmjs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: Genez-io/genezio-github-action@v2
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy
        env:
          MY_CUSTOM_SECRET: ${{ secrets.MY_CUSTOM_SECRET }}
        run: MY_SECRET=$MY_CUSTOM_SECRET genezio deploy
