name: Create release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            name: Release ${{ github.ref_name }}
            tag_name: ${{ github.ref_name }}
            token: ${{secrets.GITHUB_TOKEN}}
            generate_release_notes: true
